language: go

go:
  - 1.4
  - 1.5
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get google.golang.org/appengine

script:
  - .util/coverage.sh
  - $HOME/gopath/bin/goveralls -coverprofile=.cover/cover.out -service=travis-ci

notifications:
  email:
    - andy@andyspohn.com
